name: Trigger Blog Rebuild
on:
  push:
    branches: [ "main" ]
    paths:
      - 'learning/*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'learning/*.md'
  workflow_dispatch:

jobs:
  ping-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify Vercel
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
